### ISSUE TITLE
Package fails to install using "npm install node-person"

### ISSUE THREAD

**Issue by JeffJassky** [01org/node-realsense#232]
**Environment**
Node version: **8.5.0**
NPM version: **5.4.2**

**Run** ```npm install node-person```

**Log**
[2017-09-24T21_39_25_453Z-debug.log](https://github.com/01org/node-realsense/files/1327801/2017-09-24T21_39_25_453Z-debug.log)

**Output**
```
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-person@0.10.1 install /home/jeff/node-test/node_modules/node-person
> node -e "require('./common/scripts/build_utils.js').runNodeGyp();"

(node:11860) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'on' of null
(node:11860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
make: Entering directory '/home/jeff/node-test/node_modules/node-person/build'
  COPY Release/obj.target/realsense_person_tracking/geni/process_idl.js
  TOUCH binding_gyp_realsense_person_tracking_target_widl_gen.intermediate
  ACTION Generating NAN C++ code from WIDL files binding_gyp_realsense_person_tracking_target_widl_gen.intermediate
  CXX(target) Release/obj.target/realsense_person_tracking/addon.o
  CXX(target) Release/obj.target/realsense_person_tracking/bounding_box2d_info.o
  CXX(target) Release/obj.target/realsense_person_tracking/common/camera-delegate/camera_delegate.o
  CXX(target) Release/obj.target/realsense_person_tracking/common/camera-delegate/camera_delegate_instance.o
../common/camera-delegate/camera_delegate.cpp:6:42: fatal error: rs/playback/playback_context.h: No such file or directory
compilation terminated.
realsense_person_tracking.target.mk:236: recipe for target 'Release/obj.target/realsense_person_tracking/common/camera-delegate/camera_delegate.o' failed
make: *** [Release/obj.target/realsense_person_tracking/common/camera-delegate/camera_delegate.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from .././worker/person_tracker_runner_proxy.h:10:0,
                 from .././person_recognition.h:15,
                 from ./Release/obj.target/realsense_person_tracking/geni/gen/nan__person_recognition.h:6,
                 from ../addon.cpp:20:
.././worker/person_tracker_adapter.h:8:29: fatal error: RealSense/Image.h: No such file or directory
compilation terminated.
realsense_person_tracking.target.mk:236: recipe for target 'Release/obj.target/realsense_person_tracking/addon.o' failed
make: *** [Release/obj.target/realsense_person_tracking/addon.o] Error 1
../common/camera-delegate/camera_delegate_instance.cpp:15:18: warning: ‘required_dummy’ defined but not used [-Wunused-variable]
 static const int required_dummy =
                  ^
rm binding_gyp_realsense_person_tracking_target_widl_gen.intermediate
make: Leaving directory '/home/jeff/node-test/node_modules/node-person/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-96-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-j" "4"
gyp ERR! cwd /home/jeff/node-test/node_modules/node-person
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-person@0.10.1 install: `node -e "require('./common/scripts/build_utils.js').runNodeGyp();"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-person@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeff/.npm/_logs/2017-09-24T21_39_25_453Z-debug.log

```

**Comment by JeffJassky** [comment]
My bad. I didn't have the SDK installed properly which is documented here: https://software.intel.com/sites/products/realsense/intro/getting_started.html
